name: Gerar APK do Flet

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK (Necessário para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Bibliotecas
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preparar arquivo Principal (main.py)
        run: cp orcamento_flet.py main.py

      - name: Construir o APK (Demora uns 5 a 10 minutos)
        run: flet build apk

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: App-3J-Solucao-APK
          path: build/apk/**/*.apk
